### ISSUE TITLE
Informal feature tracker

### ISSUE THREAD

**Issue by veilm** [michaelskyba/hisshi#1]
> *We do these things not because they are easy, but because we thought they were going to be easy.*

- [x] Basic input script file reading
- [x] Basic absolute path command execution
- [x] Basic PATH lookups
- [ ] Control flow
    - [x] Indentation+dash system
    - [ ] && and || with paren ordering maybe
    - [ ] ! for NOT
- [ ] rc
  - [x] alias
  - [ ] cd wrapper with OLDPWD and home
- [ ] Builtins
    - [x] cd
    - [x] exit
    - [x] eval
    - [ ] TODO consider removing eval? If we have arg expansion, can `$$(echo echo 1)` just work?
    - [ ] loops: continue, break
    - [ ] functions: return. shift might be useless (1738727358 functions aren't supposed to know whether they're functions or not. but maybe `return` just exits the parse_script call without an actual exit())
    - [ ] job control: bg, fg, jobs, exec, trap, wait
    - [x] yeah you'll probably need export and unset even if they sound cringe
- [ ] Helper functional Unix utils
    - [x] eq: check if stdin is equal to given $1
    - [x] something to check if there is any input, like ``| rg "."``
    - [ ] Just look at more scripts to think of more
- [x] Basic piping
- [ ] Child and parent loops
    - [ ] WAIT what if instead of support loops we just have xargs? If not we still want a better xargs, to use in other shells too. Maybe just make % the default insert, but allow overwriting. And make it run for each line in stdin by default, with a flag to overwrite (in which case the whole thing including newlines is inserted)
- [x] Basic file redirection
    - [x] Decide on exact syntax. Do we want it left to right? "cmd < file" is easier to parse, though, isn't it
    - [x] Stdin, stdout
    - [ ] Arbitrary 2>&1 etc.
- [ ] Variables
    - [x] Setting
    - [x] Function-level scope
    - [x] Accepting CLI args to scripts
    - [x] Simple insertion (i.e. `echo $foo` works)
    - [ ] Slightly lower priority: string insertion (i.e. `echo "foo $bar baz"` works) (1738727395 maybe with our pf alias, doing `pf "foo %s baz" $bar` is already fine? We could shorten the %s to just % or something if you reimplement printf, since we don't really use the other templates. It feels way cleaner, in a way. But if you decide not to, it's still at least lower priority)
    - [ ] Lower priority: expansion (~`head $$foo`) (1739373497 I think you can just kind of use eval and printf) 
    - [x] Forcing local variables with _myvar
- [ ] Subshell insertion/expansion
- [x] Functions
   - [x] Indentation, multiline
   - [x] Single line
   - [x] Overwriting scope
   - [x] Forcing local with _myfunc (1733182634 btw functions with ints as names are supported and local)
- [ ] Quick temporary file management? Decide. Or just a shipped function for convenience? What interface do you want?
- [ ] Interactive usage
    - [ ] Client + server
    - [ ] POC Kakoune
- [ ] Polish
    - [x] #2
    - [ ] Misc TODOs in different files
    - [x] Use .h headers
    - [ ] Bearable error handling (e.g. I haven't even tested any `echo test | cmdnotfound | cat`)
    - [ ] Docs
        - [ ] Main
        - [ ] Dedicated web page?
